name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run the linter
        run: ./gradlew :app:checkstyleMain

      - name: Run test suite
        run: ./gradlew test

      - name: Build with Gradle wrapper
        run: ./gradlew build